### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by InDieTasten** [InDieTasten/ASCII-mate#35]
The repo doesn't contain a license yet. It should be MIT with the author being "InDieTasten", 2024

**Comment by mpa-LHutchinson** [comment]
Hi there, can you assign this issue to me and add the hacktoberfest label to it? I will get working on it as soon as I can today.

**Comment by InDieTasten** [comment]
@mpa-LHutchinson The entire repo got the topic, so it will count :)

**Comment by mpa-LHutchinson** [comment]
@InDieTasten I updated this issue with pull request #41

**Comment by InDieTasten** [comment]
@mpa-LHutchinson If you use magic words like "Closes" or "Fixes" and then the issue number in the PR description, it will auto-link the PR and also close the issue automatically, when it is merged. Something to keep in mind for future contributions :)

**Comment by mpa-LHutchinson** [comment]
Ok, thanks for letting me know!
